---
after_success:
  - "if [[ \"$TASK_TESTS_COVERAGE\" = 1 ]]; then bash < (curl -s https://codecov.io/bash); fi"
before_install:
  - "phpdbg --version 2> /dev/null || export TASK_TESTS_COVERAGE=0"
  - "phpenv config-rm xdebug.ini || return 0"
  - "travis_retry composer self-update"
  - "composer global show -ND 2>&1 | grep \"hirak/prestissimo\" || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo"
cache:
  directories:
    - $HOME/.composer
env:
  global:
    - "DEFAULT_COMPOSER_FLAGS=\"--no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable\""
    - TASK_TESTS_COVERAGE=1
  matrix:
    - DEPENDENCIES=high
    - DEPENDENCIES=low
install:
  - "if [[ \"$DEPENDENCIES\" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi"
  - "if [[ \"$DEPENDENCIES\" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi"
language: php
php:
  - 7.0
  - 7.0snapshot
  - 7.1
  - 7.1snapshot
script:
  - "./vendor/bin/grumphp run"
  - "if [[ \"$TASK_TESTS_COVERAGE\" = 1 ]]; then phpdbg -qrr ./vendor/bin/phpunit --coverage-clover=coverage.xml; fi"
sudo: false
